columns:
    id:
        label: Id
        name: id
        type: integer
        builder: simple
        options:
            listable: true
            editable: false
            sortable: true
            filterable: true
    username:
        label: Login
        name: username
        type: string
        builder: simple
        options:
            listable: true
            editable: true
            sortable: true
            filterable: true
    name:
        label: Full name
        name:  getName
        type:  string
        builder: simple
        options:
            listable: true
            editable: false
            sortable: true
            filterable: true
    email:
        label: Email
        name: email
        type: string
        builder: simple
        options:
            listable: true
            editable: true
            sortable: true
            filterable: true
    enabled:
        label: Enabled
        name: enabled
        type: boolean
        builder: simple
        options:
            listable: false
            editable: true
            sortable: true
            filterable: true
    groups:
        label: Groups
        name: groups
        type: collection
        builder: simple
        options:
            listable: true
            editable: true
            sortable: true
            filterable: true
    plainPassword:
        label: PlainPassword
        name: plainPassword
        type: string
        builder: simple
        options:
            listable: false
            editable: true
            sortable: true
            filterable: true
actions:
    is_active:
        name: enabled
        route:   admin_users_enable
        extends: is_active
        getter: getEnabled
        setter: setEnabled
    stat:
        label: Statistics
        name:  stat
        route: admin_users_stat
        builder: object
        options:
            route_with_id: true
            confirmation:  false
    logs:
        label: Logs
        name:  logs
        route: admin_users_logs
        builder: object
        options:
            route_with_id: true
            confirmation:  false
    new:
        route: admin_users_new
        extends: new
    edit:
        route: admin_users_edit
        extends: edit
    delete:
        route: admin_users_delete
        extends: delete
